apiVersion: servicebinding.io/v1beta1
kind: ServiceBinding
metadata:
  name: angular-frontend-backend-api
  namespace: mae
spec:
  env:
  - key: backend_service_url
    name: backend_service_url
  name: runtime-config
  service:
    apiVersion: v1
    kind: Secret
    name: runtime-config
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: angular-frontend