apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: angular-frontend
  namespace: mae
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: angular-frontend
spec:
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
    - name: scanning_source_policy
      value: lax-scan-policy
    - name: scanning_image_policy
      value: lax-scan-policy
    - name: testing_pipeline_matching_labels
      value:
        apps.tanzu.vmware.com/language: angular
  env:
    - name: API_BACKEND
      value: "http://java-rest-service-azure.mae.svc"
  source:
    git:
      url: https://github.com/Mpluya/angular-frontend
      ref:
        branch: main
