apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: angular-frontend
  namespace: mae
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: angular-frontend
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
    - name: clusterBuilder
      value: full
    - name: scanning_source_policy
      value: lax-scan-policy
    - name: scanning_image_policy
      value: lax-scan-policy
    - name: testing_pipeline_matching_labels
      value:
        apps.tanzu.vmware.com/language: angular
  build:
    env:
    - name: BP_NODE_RUN_SCRIPTS
      value: build
    - name: NODE_ENV
      value: development
    - name: BP_WEB_SERVER
      value: nginx
    - name: BP_WEB_SERVER_ROOT
      value: dist/angular-frontend
    - name: BP_WEB_SERVER_ENABLE_PUSH_STATE
      value: true
  source:
    git:
      url: https://github.com/Mpluya/angular-frontend
      ref:
        branch: main
